config/routes.rb
Cs::Application.routes.draw do
  
  get "posts/index"

  root to: 'pages#home'

  match '/contact',  to: 'pages#contact'
  match '/nieuws', to: 'posts#index'
  
  namespace :admin do
    root :to => "posts#index"
    resources :posts
  end

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  body       :text
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  attr_accessible :title, :body, :teaser, :publish_date
  
  validates :title, presence: true
  validates :body, presence: true
  validates :teaser, presence: true
  validates :publish_date, presence: true
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < InheritedResources::Base
  
  def index
    @posts = Post.all( :order => "publish_date DESC")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.all( :order => "created_at DESC", :limit => "2")
  end

  def contact
    
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.all( :order => "publish_date DESC")
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.haml
.row
	.span6
		= form_for([:admin, @post]) do |f|
			= render 'layouts/shared/error_messages'
			= f.label "Titel"
			= f.text_field :title
			
			= f.label "Teaser"
			= f.text_area :teaser, :class => "tinymce", :rows => "10"
			%br/
			
			= f.label "Bericht"
			= f.text_area :body, :class => "tinymce"
			= tinymce
			%br/
			
			= f.label "Publiceerdatum"
			= f.datetime_select :publish_date, :default => Time.now
			%br/
			
			= f.submit "Opslaan"

app/views/admin/posts/edit.html.haml
= provide(:title, 'Bewerk nieuwsbericht')

%p= link_to 'terug naar alle nieuwsberichten', admin_posts_path

%h1 Bewerk nieuwsbericht

= render "form"

app/views/admin/posts/index.html.haml
= provide(:title, 'Nieuwsberichten')

%h1 Nieuwsberichten
%p
	.btn= link_to 'Niew nieuwsbericht »', new_admin_post_path
	
%table.table
	%thead
		%tr
			%th Datum
			%th Titel
			%th Acties
	%tbody
		- @posts.each do |post|
			%tr
				%td= post.publish_date.strftime("%d/%m/%Y")
				%td= link_to post.title, admin_post_path(post)
				%td
					= link_to "Bewerken", edit_admin_post_path(post)
					|					
					= link_to "Verwijderen", admin_post_path(post), method: :delete, data: { confirm: "Nieuwsbericht verwijderen?" }

app/views/admin/posts/new.html.haml
= provide(:title, 'Nieuw nieuwsbericht')

%p= link_to 'terug naar alle nieuwsberichten', admin_posts_path

%h1 Nieuw nieuwsbericht

= render "form"

app/views/admin/posts/show.html.haml
%p= link_to 'terug naar alle nieuwsberichten', admin_posts_path

%h1= @post.title

%p= raw(@post.teaser)
%p= raw(@post.body)

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container">

    <div class="row">
      <div class="span4">
        <h4>Over Creatief Schrijven</h4>
        <p class="quiet">
		  		<%= link_to 'Missie', '#' %>
          <br/>
          <%= link_to 'Wie is Wie', '#' %>
          <br/>
          <%= link_to 'Vacatures', '#' %>
          <br/>
          <%= link_to 'Bankgegevens', '#' %>
		  		<br/>
		  		<%= link_to 'Vrijwilligers', '#' %>
        </p>
      </div>
      <div class="span4">
        <h4>VERZ!N</h4>
        <p class="quiet">
          <%= link_to 'Bestel', '#' %>
          <br/>
		  		<%= link_to 'Schrijfuitdaging', '#' %>
          <br/>
          <%= link_to 'Vorige nummers', '#' %>
          <br/>
          <%= link_to 'Contacteer de redactie', '#' %>
        </p>
      </div>
      <div class="span4">
        <h4>Contact</h4>
        <p class="quiet">
          E: info@creatiefschrijven.be
          <br/>
          T: +32 03 229 09 90
		  		<br/>
		  		Waalsekaai 15 - 2000 Antwerpen
        </p>		
				<h4>Downloads</h4>
				<p class="quiet">
					<%= link_to 'Schrijf- en wedstrijdbrochure', '#' %>
					<br/>
					<%= link_to 'Tekstbrochures', '#' %>
					<br/>
					<%= link_to 'Logo', '#' %>
					<br/>
				</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Creatief Schrijven | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<!--[if lt IE 9]>
	<script scr="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<!--[endif]-->
</head>
<body>
	<header class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<nav>
					<%= link_to image_tag('logo.png', :size  => "50x50"), root_path %>
					<ul class="nav pull-right">
						<li><%= link_to "Nieuws", nieuws_path %></li>
						<li><%= link_to "Cursussen", '#' %></li>
						<li><%= link_to "Wedstrijden", '#' %></li>
						<li class="dropdown"><%= link_to "Schrijfadvies", '#', data: {toggle: "dropdown"}, class: "dropdown-toggle" %></li>
							<ul class="dropdown-menu">
								<li>manuscriptbeoordeling</li>
								<li>contacteer onze schrijfconsulent</li>
							</ul>
						</li>
						<li><%= link_to "Kennisbank", '#' %></li>
						<li><%= link_to "Contact", contact_path %></li>
					</ul>
				</nav>
			</div>
		</div>
	</header>
	<div class="container">
		<% flash.each do  |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/shared/_error_messages.html.haml
= if @post.errors.any?
	#error_explanation
		.alert.alert-error
			Het formulier bevat de volgende fout(en):
			#ul
				- @post.errors.full_messages.each do |msg|
					#li
						* 
						= msg

app/views/pages/contact.html.haml
= provide(:title, 'Contact')

%h1 Pages#contact
%p Find me in app/views/pages/contact.html.haml

app/views/pages/home.html.haml
= provide(:title, 'Home')

.row
  .span6
    %h1 Creatief Schrijven is hét aanspreekpunt voor iedereen die schrijven niet laten kan
    %br/
    .a.btn.btn-primary.btn-large Schrijf je in op onze nieuwsbrief »
    %br/
    %br/
    =image_tag 'alledagendichten.png', :size  => '200x200'
      
  .span6
    .home-nieuws
      - @posts.each do |post|
        %h2= link_to post.title, nieuws_path
        %p
          = raw(post.teaser)
          = link_to 'Lees meer', nieuws_path

      .btn= link_to 'Meer nieuwsberichten »', nieuws_path

%br/
%br/
.row
  .span4
    %h3
      %strong Schrijfcursussen
    %p
      .btn= link_to 'Op zoek naar een cursus? »', '#'
      %br/
      %br/
      %ul
        %li= link_to 'Zakelijk Schrijven', '#'
        %li= link_to 'Schrijven voor het web', '#'
        %li= link_to 'Poëzie voor beginners', '#'
  .span4
    %h3
      %strong Schrijfwedstrijden
    %p
      .btn= link_to 'Op zoek naar een wedstrijd? »', '#'
      %br/
      %br/
      %ul
        %li= link_to 'Haikuwedstrijd', '#'
        %li= link_to 'Kunstbende TXT', '#'
        %li= link_to 'Prijzen van de provincie Oost-Vlaanderen voor Letterkunde', '#'
			
  .span4
    %h3
      %strong Informatie
    %p
      %br/
      Hier vind je snelle links naar informatie over:
      %ul
        %li= link_to 'Manuscriptbeoordeling', '#'
        %li= link_to 'Print On Demand uitgevers', '#'
        %li= link_to 'Schrijfdocentenopleiding', '#'

app/views/posts/index.html.haml
= provide(:title, 'Nieuws')

%h1 Nieuws

- @posts.each do |post|
		.news_item
		%h2.post_title= post.title
		.date= post.publish_date.strftime("%d/%m/%Y")
		.news_teaser= raw(post.teaser)
		.news_body= raw(post.body)